language: node_js
node_js: node
services: 
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: TWzrBciMXbzAOMgraVC3qLHdKuo9WSPjWS5N8VUDo8bqOLR0jgLE1KXKU7m71epOaC+sa+enqpbQaq8OOWiWDZswu9ADmkrHuPd7ky8zM+03m7PdVob9KtNnva6LfN4uWQyfRWgFayo0PIbjvY8qgxySEutYVM+l1S4fWHObQVNecw6drylL7HGwgd1zrxpT+MlxBi2lnsHjxed8k+Wrl4Zsr2nUno+HEiTrhqAVxcsqDkViB9PJWNtVKykJuU303TaKhzLvUmwhtl+lk9+hPH7/jfaG7X2cEaE3AmhyO9jSZpstvG/+F+A9dyw94arJ7WhYb0hi6fn1e0fMS4CYhJp7K411HqAr/5L0dr3ja5DiDqsDESPDh8DykyNTCwcmTpVDxcEJ/YBShhhoPF3alpCkiJLdf8L1XbNB9pRZjOXIbeaANlElc1Nh8R/mIPoKQQxtD2Fsx4PT3lvxkErt2J1JWGRkr3pUti4uZsSbYs1DkGENGpqkupsuHRNR0sWhcMtqkf0Iuoom1UOkYpm1TCar6VQU5Xs2kmmoDma3TbxK5rZa9Nwbg1zqLwIBqayXqMWxQjBKfYtrW4hPtwYg5qW6Y1juIOzKdrRn0z0piOfU5a1uwhmNKohDK/9leG2nh/TQjpAyJLCgioOUIoKom/ulOd76riyXeKBV6hVe/8c=
  app: stormy-scrubland-50634
  on:
    repo: nbradf2/garden-planner-capstone